### ISSUE TITLE
Add Menu Screen for Dodger

### ISSUE THREAD

**Issue by desttinghim** [Geemili/zig-game-clones#1]
There should be a menu screen for selecting play, looking at high scores, and possibly changing settings. [Nuklear](https://github.com/Immediate-Mode-UI/Nuklear) may be a good library for implementing this. [KiWi](https://github.com/mobius3/KiWi) looks interesting as well, though the README suggests it isn't stable.

**Comment by desttinghim** [comment]
Since Nuklear isn't an option due to its reliance on macros, we might just want to roll a very basic GUI with just buttons + text. @Geemili

**Comment by leroycep** [comment]
It's not macros I had issues with, it's with multiple enum tags being assigned the same value (which is fixed in the master branch of zig) and the compiler terminating unexpectedly (which I got on the master branch of zig).

KiWi does look interesting. And seeing how the language that we are using is itself unstable, I don't see a problem in adding a library that's unstable ;)

**Comment by leroycep** [comment]
After a couple hours of trying to get nuklear to with zig, I believe that any effort will require some editing of nuklear's source code. I believe that Hejsil has done this for his project [metronome][1]. He has a fork of nuklear [here][2].

I've [started a branch][3] that begins to implement nuklear by copying what Hejsil has done. If we want to pursue this further, try using Hejsil's fork of Nuklear instead of the one I included on that branch. Perhaps we should send Hejsil a DM and ask him for help?

Also, I should mention that I've gotten OpenGLES2 to work in the template project on the master branch. It doesn't render anything to the screen, it just clears the screen with red, but that should be enough to build off of, if we want to go that direction.

[1]: https://github.com/TM35-Metronome/metronome
[2]: https://github.com/Hejsil/Nuklear-1
[3]: https://github.com/Geemili/zig-game-clones/tree/nuklear-gui

**Comment by leroycep** [comment]
I've switched my efforts to getting KiWi working, to great success! I was able to render a label to the screen, and then get a button working. In addition to getting KiWi working, I was able to create a `Screen` struct that can be extended! :smile: 

All of this work is on the `kiwi-gui` branch. Tomorrow I'll merge that branch into master (unless you do it first) and then work on putting everything into the dodger game.
